"""added pub_date field

Revision ID: a6435c4bb609
Revises: 85080ae26b56
Create Date: 2023-11-14 18:06:36.384715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6435c4bb609'
down_revision: Union[str, None] = '85080ae26b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('pub_date', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'pub_date')
    # ### end Alembic commands ###
